force-app/main/default/objects/Clicks_Saved__c/Clicks_Saved__c.object-meta.xml
<CustomObject>
    <label>Clicks Saved</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Clicks Saved</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clicks Saved</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clicks_Saved__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Cumulative Clicks Saved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shortcut__mdt/Shortcut__mdt.object-meta.xml
<CustomObject>
    <label>Shortcut</label>
    <pluralLabel>Shortcuts</pluralLabel>
</CustomObject>

force-app/main/default/classes/ShortcutsService.cls
/**
 * @description       : Apex controller for shortcuts LWC.
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 03-04-2022
 * @last modified by  : Ben Learn
**/
public class ShortcutsService {
    @AuraEnabled
    public static void updateClicksCount(String link) {
        List<Clicks_Saved__c> csList = [SELECT Id, Count__c FROM Clicks_Saved__c];
        Integer clicksSaved = 0;
        switch on link {
            when 'Setup' {
                clicksSaved = 1;
            } when 'Object Manager' {
                clicksSaved = 2;
            } when else {
                clicksSaved = 3;

            }
        }
        if(csList.size() == 0){
            csList.add(new Clicks_Saved__c(Count__c=clicksSaved));
        } else {
            csList[0].Count__c += clicksSaved;
        }
        upsert csList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Clicks_Saved__c> getClicksId() {
        return [SELECT Id FROM Clicks_Saved__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Shortcut__mdt> getShortcuts() {
        return [SELECT MasterLabel, Icon__c, URL__c FROM Shortcut__mdt];
    }
}