force-app/main/default/objects/Clicks_Saved__c/Clicks_Saved__c.object-meta.xml
<CustomObject>
    <label>Clicks Saved</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Clicks Saved</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clicks Saved</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clicks_Saved__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Cumulative Clicks Saved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ShortcutButtonsController.cls
public class ShortcutButtonsController {
    @AuraEnabled
    public static void updateClicksCount() {
        List<Clicks_Saved__c> csList = [SELECT Id, Count__c FROM Clicks_Saved__c];
        if(csList.size() == 0){
            csList.add(new Clicks_Saved__c(Count__c=1));
        } else {
            csList[0].Count__c += 1;
        }
        upsert csList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Clicks_Saved__c> getClicksId() {
        return [SELECT Id FROM Clicks_Saved__c];
    }
}